---
requires_version: true

variables:
    firstname_attribute_id: 'select attribute_id from eav_attribute where attribute_code = "firstname" and entity_type_id = 1'
    middlename_attribute_id: 'select attribute_id from eav_attribute where attribute_code = "middlename" and entity_type_id = 1'
    lastname_attribute_id: 'select attribute_id from eav_attribute where attribute_code = "lastname" and entity_type_id = 1'
    dob_attribute_id: 'select attribute_id from eav_attribute where attribute_code = "dob" and entity_type_id = 1'
    password_hash_attribute_id: 'select attribute_id from eav_attribute where attribute_code = "password_hash" and entity_type_id = 1'

tables:
    api_session:
        truncate: true

    core_cache:
        truncate: true

    core_cache_tag:
        truncate: true

    core_session:
        truncate: true

    dataflow_batch:
        truncate: true

    dataflow_batch_export:
        truncate: true

    dataflow_batch_import:
        truncate: true

    dataflow_import_data:
        truncate: true

    dataflow_profile_history:
        truncate: true

    dataflow_session:
        truncate: true

    index_event:
        truncate: true

    log_*:
        truncate: true

    persistent_session:
        truncate: true

    report_event:
        truncate: true

    sendfriend_log:
        truncate: true

    '*_tmp':
        truncate: true

    '*_idx':
        truncate: true

    admin_user:
        converters:
            email:
                converter: 'randomizeEmail'
                unique: true
            username:
                converter: 'randomizeText'
                unique: true
            firstname:
                converter: 'anonymizeText'
            lastname:
                converter: 'anonymizeText'
            password:
                converter: 'randomizeText'

    customer_entity:
        converters:
            email:
                converter: 'randomizeEmail'
                unique: true

    customer_entity_datetime:
        converters:
            value:
                ## dob (11)
                converter: 'anonymizeDateTime'
                condition: '{{attribute_id}} == @dob_attribute_id'

    customer_entity_varchar:
        converters:
            value:
                converter: chain
                parameters:
                    converters:
                        - converter: 'anonymizeText'
                          condition: '{{attribute_id}} == @firstname_attribute_id || {{attribute_id}} == @middlename_attribute_id || {{attribute_id}} == @lastname_attribute_id'
                        - converter: 'randomizeText'
                          condition: '{{attribute_id}} == @password_hash_attribute_id'

    newsletter_subscriber:
        converters:
            subscriber_email:
                converter: 'randomizeEmail'
            subscriber_confirm_code:
                converter: 'randomizeText'

    # Not anonymized: title, detail
    review_detail:
        converters:
            nickname:
                converter: 'anonymizeText'

    sales_flat_creditmemo_comment:
        converters:
            comment:
                converter: 'anonymizeText'

    sales_flat_creditmemo_grid:
        converters:
            billing_name:
                converter: 'anonymizeText'

    sales_flat_invoice_comment:
        converters:
            comment:
                converter: 'anonymizeText'

    sales_flat_invoice_grid:
        converters:
            billing_name:
                converter: 'anonymizeText'

    # Not anonymized: customer_prefix, customer_suffix, customer_gender, coupon_code
    sales_flat_order:
        converters:
            customer_email:
                converter: 'randomizeEmail'
            customer_firstname:
                converter: 'anonymizeText'
            customer_middlename:
                converter: 'anonymizeText'
            customer_lastname:
                converter: 'anonymizeText'
            customer_dob:
                converter: 'anonymizeDateTime'
            customer_note:
                converter: 'anonymizeText'
            remote_ip:
                converter: 'faker'
                parameters:
                    formatter: 'ipv4'

    # Not anonymized: prefix, suffix, region, region_id, country_id
    sales_flat_order_address:
        converters:
            email:
                converter: 'randomizeEmail'
            firstname:
                converter: 'anonymizeText'
            middlename:
                converter: 'anonymizeText'
            lastname:
                converter: 'anonymizeText'
            company:
                converter: 'anonymizeText'
            street:
                converter: 'anonymizeText'
            postcode:
                converter: 'randomizeNumber'
            city:
                converter: 'anonymizeText'
            telephone:
                converter: 'randomizeNumber'
            fax:
                converter: 'randomizeNumber'

    sales_flat_order_grid:
        converters:
            billing_name:
                converter: 'anonymizeText'
            shipping_name:
                converter: 'anonymizeText'

    # Not anonymized: cc_exp_month, cc_exp_year, cc_ss_start_month, cc_ss_start_year
    sales_flat_order_payment:
        converters:
            last_trans_id:
                converter: 'anonymizeNumber'
            cc_trans_id:
                converter: 'anonymizeNumber'
            cc_owner:
                converter: 'anonymizeText'
            cc_approval:
                converter: 'anonymizeText'
            cc_number_enc:
                converter: 'anonymizeText'
            cc_last4:
                converter: 'anonymizeNumber'
            cc_debug_request_body:
                converter: 'anonymizeText'
            cc_debug_response_body:
                converter: 'anonymizeText'
            cc_debug_response_serialized:
                converter: 'anonymizeText'
            echeck_account_name:
                converter: 'anonymizeText'
            echeck_bank_name:
                converter: 'anonymizeText'
            additional_information:
                converter: 'serializedData'
                parameters:
                    converters:
                        CC_CN:
                            converter: 'anonymizeText'

    # Not anonymized: customer_prefix, customer_suffix ,customer_gender, coupon_code
    sales_flat_quote:
        converters:
            customer_email:
                converter: 'randomizeEmail'
            customer_firstname:
                converter: 'anonymizeText'
            customer_middlename:
                converter: 'anonymizeText'
            customer_lastname:
                converter: 'anonymizeText'
            customer_dob:
                converter: 'anonymizeDateTime'
            customer_note:
                converter: 'anonymizeText'
            remote_ip:
                converter: 'faker'
                parameters:
                    formatter: 'ipv4'
            password_hash:
                converter: 'setNull'

    # Not anonymized: prefix, suffix, region, region_id, country_id
    sales_flat_quote_address:
        converters:
            email:
                converter: 'randomizeEmail'
            firstname:
                converter: 'anonymizeText'
            middlename:
                converter: 'anonymizeText'
            lastname:
                converter: 'anonymizeText'
            company:
                converter: 'anonymizeText'
            street:
                converter: 'anonymizeText'
            postcode:
                converter: 'randomizeNumber'
            city:
                converter: 'anonymizeText'
            telephone:
                converter: 'randomizeNumber'
            fax:
                converter: 'randomizeNumber'
            customer_notes:
                converter: 'anonymizeText'

    # Not anonymized: cc_exp_month, cc_exp_year, cc_ss_start_month, cc_ss_start_year
    sales_flat_quote_payment:
        converters:
            cc_owner:
                converter: 'anonymizeText'
            cc_number_enc:
                converter: 'anonymizeText'
            cc_last4:
                converter: 'anonymizeNumber'
            additional_information:
                converter: 'serializedData'
                parameters:
                    converters:
                        CC_CN:
                            converter: 'anonymizeText'

    sales_flat_shipment_comment:
        converters:
            comment:
                converter: 'anonymizeText'

    sales_flat_shipment_grid:
        converters:
            shipping_name:
                converter: 'anonymizeText'

    sales_flat_shipment_track:
        converters:
            track_number:
                converter: 'anonymizeText'
