---
extends: magento2_commerce

tables:
    company:
        # Not anonymized: region, region_id, country_id
        converters:
            company_email:
                converter: 'randomizeEmail'
            company_name:
                converter: 'anonymizeText'
            legal_name:
                converter: 'anonymizeText'
            comment:
                converter: 'anonymizeText'
            street:
                converter: 'anonymizeText'
            city:
                converter: 'anonymizeText'
            postcode:
                converter: 'randomizeNumber'
            telephone:
                converter: 'randomizeNumber'
            reject_reason:
                converter: 'anonymizeText'

    company_advanced_customer_entity:
        converters:
            telephone:
                converter: 'randomizeNumber'

    company_credit_history:
        converters:
            comment:
                converter: 'anonymizeText'

    company_order_entity:
        converters:
            company_name:
                converter: 'anonymizeText'

    negotiable_quote_comment:
        converters:
            comment:
                converter: 'anonymizeText'

    negotiable_quote_grid:
        converters:
            company_name:
                converter: 'anonymizeText'
            sales_rep:
                converter: 'anonymizeText'
