---
extends: 'magento2'
version: '2.3.3'

database:
    user: 'magento2'
    password: '7fd8r6cmy5wrhu2m'
    name: 'magento2'

dump:
    output: 'magento2-{Y-m-d H:i:s}.sql.bz2'
    compress: 'bzip2'

tables:
    customer_entity:
        filters:
            - ['email', 'like', '@smile.fr']

    quote:
        filters:
            - ['created_at', 'gt', 'expr: date_sub(now(), interval 60 day)']

    sales_order:
        filters:
            - ['created_at', 'gt', 'expr: date_sub(now(), interval 60 day)']

    my_custom_table:
        converters:
            email:
                converter: 'randomizeEmail'
                unique: true
