---
extends: 'magento2'
version: '2.3.2'

database:
    user: 'magento2'
    password: '7fd8r6cmy5wrhu2m'
    name: 'magento2'

dump:
    output: 'magento2-{Y-m-d H:i:s}.sql.bz2'
    compress: 'bzip2'

tables:
    my_custom_table:
        converters:
            email:
                converter: 'randomizeEmail'
                unique: true
