---
extends: 'magento2'
version: '2.3.4'

database:
    user: 'magento2'
    password: '7fd8r6cmy5wrhu2m'
    name: 'magento2'

dump:
    output: 'magento2-{Y-m-d H:i:s}.sql.bz2'
    compress: 'bzip2'

tables:
    # Don't anonymize emails/passwords belonging to the "Acme" company
    admin_user:
        converters:
            email:
                condition: 'strpos({{email}}, "@acme.fr") === false'
            password:
                condition: 'strpos({{email}}, "@acme.fr") === false'

    # Dump only recent quotes
    quote:
        filters:
            - ['created_at', 'gt', 'expr: date_sub(now(), interval 60 day)']

    # Dump only recent orders
    sales_order:
        filters:
            - ['created_at', 'gt', 'expr: date_sub(now(), interval 60 day)']

    # Anonymize a table named "my_custom_table"
    my_custom_table:
        converters:
            email:
                converter: 'randomizeEmail'
                unique: true
