---
parameters:
    config.schema_file: '%app_root%/app/config/schema.json'
    config.templates_dir: '%app_root%/app/config/templates'
    faker.locale: 'en_US'

services:
    _defaults:
        autowire: false # explained in AppKernel::buildContainer
        autoconfigure: false # not useful in this app

    command.compile:
        class: 'Smile\GdprDump\Console\Command\CompileCommand'
        public: true
        arguments:
            - '%faker.locale%'

    command.dump:
        class: 'Smile\GdprDump\Console\Command\DumpCommand'
        public: true
        arguments:
            - '@dumper'
            - '@dumper.config'
            - '@dumper.config_loader'
            - '@config.schema_validator'

    config.file_locator:
        class: 'Smile\GdprDump\Config\Loader\FileLocator'
        arguments:
            - '%config.templates_dir%'

    config.parser:
        class: 'Smile\GdprDump\Config\Parser\YamlParser'

    config.schema_validator:
        class: 'Smile\GdprDump\Config\Validator\JsonSchemaValidator'
        arguments:
            - '%config.schema_file%'

    converter.factory:
        class: 'Smile\GdprDump\Converter\ConverterFactory'
        arguments:
            - '@converter.resolver'
            - '@faker.service'

    converter.resolver:
        class: 'Smile\GdprDump\Converter\ConverterResolver'

    dumper:
        class: 'Smile\GdprDump\Dumper\MysqlDumper'
        public: true # used by functional tests
        arguments:
            - ['@dumper.data_converter_extension', '@dumper.table_filter_extension']

    dumper.config:
        class: 'Smile\GdprDump\Config\Config'

    dumper.config_loader:
        class: 'Smile\GdprDump\Config\Loader\ConfigLoader'
        public: true # used by functional tests
        arguments:
            - '@dumper.config'
            - '@config.parser'
            - '@config.file_locator'

    dumper.data_converter_extension:
        class: 'Smile\GdprDump\Dumper\Mysql\DataConverterExtension'
        arguments:
            - '@converter.factory'
            - '@faker.service'

    dumper.table_filter_extension:
        class: 'Smile\GdprDump\Dumper\Mysql\TableFilterExtension'

    faker.service:
        class: 'Smile\GdprDump\Faker\FakerService'
        public: true # used by functional tests
        arguments:
            - '%faker.locale%'
