---
parameters:
    config.schema_file: '%app_root%/app/config/schema.json'
    config.templates_dir: '%app_root%/app/config/templates'
    faker.locale: 'en_US'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Discover services
    Smile\GdprDump\:
        resource: '../../src/'
        exclude: '../../src/{AppKernel.php,Compiler.php}'

    # Console commands have public visibility, they are fetched from the container in the AppKernel class
    Smile\GdprDump\Console\Command\:
        resource: '../../src/Console/Command'
        public: true

    # Services with data binding
    Smile\GdprDump\Config\Validator\JsonSchemaValidator:
        bind:
            $schemaFile: '%config.schema_file%'

    Smile\GdprDump\Config\Resolver\PathResolver:
        bind:
            $templatesDirectory: '%config.templates_dir%'

    Smile\GdprDump\Faker\FakerService:
        bind:
            $options:
                locale: '%faker.locale%'
