---
extends: 'magento2'
version: '2.3.0'

database:
    user: 'magento2'
    password: '7fd8r6cmy5wrhu2m'
    name: 'magento2'

dump:
    compress: 'bzip2'
    output: 'php://stdout'

tables:
    my_custom_table:
        converters:
            email:
                converter: 'randomizeEmail'
                unique: true
