---
requiresVersion: true

tables:
    cache_*:
        truncate: true

    sessions:
        truncate: true

    users_field_data:
        converters:
            mail:
                converter: 'obfuscateEmail'
            init:
                converter: 'obfuscateEmail'
                unique: true
            name:
                converter: 'obfuscateText'
                unique: true
            pass: 'anonymizeText'
