---
requiresVersion: true

tables:
    cache:
        truncate: true

    cache_*:
        truncate: true

    sessions:
        truncate: true

    users:
        converters:
            mail:
                converter: 'anonymizeEmail'
                unique: true
                parameters: {method: 'replace'}
            init:
                converter: 'anonymizeEmail'
                unique: true
                parameters: {method: 'replace'}
            name:
                converter: 'anonymizeText'
                unique: true
                parameters: {method: 'replace'}
            pass: 'anonymizeText'
