---
requiresVersion: true

tables:
    cache:
        truncate: true

    cache_*:
        truncate: true

    sessions:
        truncate: true

    users:
        converters:
            mail: 'randomizeEmail'
            init:
                converter: 'randomizeEmail'
                unique: true
            name:
                converter: 'randomizeText'
                unique: true
            pass: 'anonymizeText'
