---
requiresVersion: true

tables:
    cache_*:
        truncate: true

    sessions:
        truncate: true

    users_field_data:
        converters:
            mail:
                converter: 'randomizeEmail'
            init:
                converter: 'randomizeEmail'
                unique: true
            name:
                converter: 'randomizeText'
                unique: true
            pass:
                converter: 'anonymizeText'
