---
extends: magento1

tables:
    enterprise_giftregistry_entity:
        converters:
            title: 'anonymizeText'
            message: 'anonymizeText'
            shipping_address:
                converter: 'serializedData'
                parameters:
                    converters:
                        firstname: 'anonymizeText'
                        middlename: 'anonymizeText'
                        lastname: 'anonymizeText'
                        company: 'anonymizeText'
                        street: 'anonymizeText'
                        postcode: 'randomizeNumber'
                        city: 'anonymizeText'
                        telephone: 'randomizeNumber'
                        fax: 'randomizeNumber'

    enterprise_giftregistry_person:
        converters:
            email: 'randomizeEmail'
            firstname: 'anonymizeText'
            middlename: 'anonymizeText'
            lastname: 'anonymizeText'

    enterprise_rma:
        converters:
            customer_custom_email: 'randomizeEmail'

    enterprise_rma_grid:
        converters:
            customer_name: 'anonymizeText'

    enterprise_rma_shipping_label:
        converters:
            track_number: 'anonymizeText'

    enterprise_rma_status_history:
        converters:
            comment: {converter: 'faker', parameters: {formatter: 'text'}}

    enterprise_sales_creditmemo_grid_archive:
        converters:
            billing_name: 'anonymizeText'

    enterprise_sales_invoice_grid_archive:
        converters:
            billing_name: 'anonymizeText'

    enterprise_sales_order_grid_archive:
        converters:
            billing_name: 'anonymizeText'
            shipping_name: 'anonymizeText'

    enterprise_sales_shipment_grid_archive:
        converters:
            shipping_name: 'anonymizeText'
