---
requiresVersion: true

tables:
    admin_user_session:
        truncate: true

    admin_passwords:
        truncate: true

    cache:
        truncate: true

    cache_tag:
        truncate: true

    customer_log:
        truncate: true

    customer_visitor:
        truncate: true

    newsletter_queue:
        truncate: true

    password_reset_request_event:
        truncate: true

    persistent_session:
        truncate: true

    report_event:
        truncate: true

    sendfriend_log:
        truncate: true

    session:
        truncate: true

    '*_tmp':
        truncate: true

    '*_idx':
        truncate: true

    admin_user:
        converters:
            email:
                converter: 'randomizeEmail'
                unique: true
            username:
                converter: 'randomizeText'
                unique: true
            firstname:
                converter: 'anonymizeText'
            lastname:
                converter: 'anonymizeText'
            password:
                converter: 'randomizeText'
            failures_num:
                converter: 'setValue'
                parameters: {value: 0}
            first_failure:
                converter: 'setNull'
            lock_expires:
                converter: 'setNull'

    # Not anonymized: prefix, suffix, gender
    customer_entity:
        converters:
            email:
                converter: 'randomizeEmail'
                unique: true
            firstname:
                converter: 'anonymizeText'
            middlename:
                converter: 'anonymizeText'
            lastname:
                converter: 'anonymizeText'
            dob:
                converter: 'anonymizeDate'
            password_hash:
                converter: 'randomizeText'
            failures_num:
                converter: 'setValue'
                parameters: {value: 0}
            first_failure:
                converter: 'setNull'
            lock_expires:
                converter: 'setNull'

    # Not anonymized: country_id, prefix, region, region_id, suffix
    customer_address_entity:
        converters:
            firstname:
                converter: 'anonymizeText'
            middlename:
                converter: 'anonymizeText'
            lastname:
                converter: 'anonymizeText'
            street:
                converter: 'anonymizeText'
            postcode:
                converter: 'randomizeNumber'
            city:
                converter: 'anonymizeText'
            telephone:
                converter: 'randomizeNumber'
            fax:
                converter: 'randomizeNumber'
            company:
                converter: 'anonymizeText'

    # Not anonymized: gender, billing_country_id, billing_region
    customer_grid_flat:
        converters:
            name:
                converter: 'anonymizeText'
            email:
                converter: 'randomizeEmail'
            dob:
                converter: 'anonymizeDate'
            shipping_full:
                converter: 'anonymizeText'
            billing_full:
                converter: 'anonymizeText'
            billing_firstname:
                converter: 'anonymizeText'
            billing_lastname:
                converter: 'anonymizeText'
            billing_company:
                converter: 'anonymizeText'
            billing_street:
                converter: 'anonymizeText'
            billing_postcode:
                converter: 'randomizeNumber'
            billing_city:
                converter: 'anonymizeText'
            billing_telephone:
                converter: 'randomizeNumber'
            billing_fax:
                converter: 'randomizeNumber'

    newsletter_subscriber:
        converters:
            subscriber_email:
                converter: 'randomizeEmail'
            subscriber_confirm_code:
                converter: 'randomizeText'

    # Not anonymized: customer_prefix, customer_suffix ,customer_gender, coupon_code
    quote:
        converters:
            customer_email:
                converter: 'randomizeEmail'
            customer_firstname:
                converter: 'anonymizeText'
            customer_middlename:
                converter: 'anonymizeText'
            customer_lastname:
                converter: 'anonymizeText'
            customer_dob:
                converter: 'anonymizeDateTime'
            customer_note:
                converter: 'faker'
                parameters: {formatter: 'text'}
            remote_ip:
                converter: 'faker'
                parameters: {formatter: 'ipv4'}
            password_hash:
                converter: 'setNull'

    # Not anonymized: prefix, suffix, region, region_id, country_id
    quote_address:
        converters:
            email:
                converter: 'randomizeEmail'
            firstname:
                converter: 'anonymizeText'
            middlename:
                converter: 'anonymizeText'
            lastname:
                converter: 'anonymizeText'
            company:
                converter: 'anonymizeText'
            street:
                converter: 'anonymizeText'
            postcode:
                converter: 'randomizeNumber'
            city:
                converter: 'anonymizeText'
            telephone:
                converter: 'randomizeNumber'
            fax:
                converter: 'randomizeNumber'
            customer_notes:
                converter: 'faker'
                parameters: {formatter: 'text'}

    # Not anonymized: cc_exp_month, cc_exp_year, cc_ss_start_month, cc_ss_start_year
    quote_payment:
        converters:
            cc_owner:
                converter: 'anonymizeText'
            cc_number_enc:
                converter: 'anonymizeText'
            cc_last_4:
                converter: 'anonymizeNumber'
            additional_information:
                converter: 'jsonData'
                parameters:
                    converters: {CC_CN: 'anonymizeText'}

    # Not anonymized: title, detail
    review_detail:
        converters:
            nickname:
                converter: 'anonymizeText'

    sales_creditmemo:
        converters:
            customer_note:
                converter: 'faker'
                parameters: {formatter: 'text'}

    sales_creditmemo_comment:
        converters:
            comment:
                converter: 'faker'
                parameters: {formatter: 'text'}

    sales_creditmemo_grid:
        converters:
            customer_email:
                converter: 'randomizeEmail'
            customer_name:
                converter: 'anonymizeText'
            billing_name:
                converter: 'anonymizeText'
            billing_address:
                converter: 'anonymizeText'
            shipping_address:
                converter: 'anonymizeText'

    sales_invoice:
        converters:
            customer_note:
                converter: 'faker'
                parameters: {formatter: 'text'}

    sales_invoice_comment:
        converters:
            comment:
                converter: 'faker'
                parameters: {formatter: 'text'}

    sales_invoice_grid:
        converters:
            customer_email:
                converter: 'randomizeEmail'
            customer_name:
                converter: 'anonymizeText'
            billing_name:
                converter: 'anonymizeText'
            billing_address:
                converter: 'anonymizeText'
            shipping_address:
                converter: 'anonymizeText'

    # Not anonymized: customer_prefix, customer_suffix, customer_gender, coupon_code
    sales_order:
        converters:
            customer_email:
                converter: 'randomizeEmail'
            customer_firstname:
                converter: 'anonymizeText'
            customer_middlename:
                converter: 'anonymizeText'
            customer_lastname:
                converter: 'anonymizeText'
            customer_dob:
                converter: 'anonymizeDateTime'
            customer_note:
                converter: 'faker'
                parameters: {formatter: 'text'}
            remote_ip:
                converter: 'faker'
                parameters: {formatter: 'ipv4'}

    # Not anonymized: prefix, suffix, region, region_id, country_id
    sales_order_address:
        converters:
            email:
                converter: 'randomizeEmail'
            firstname:
                converter: 'anonymizeText'
            middlename:
                converter: 'anonymizeText'
            lastname:
                converter: 'anonymizeText'
            company:
                converter: 'anonymizeText'
            street:
                converter: 'anonymizeText'
            postcode:
                converter: 'randomizeNumber'
            city:
                converter: 'anonymizeText'
            telephone:
                converter: 'randomizeNumber'
            fax:
                converter: 'randomizeNumber'

    sales_order_grid:
        converters:
            customer_email:
                converter: 'randomizeEmail'
            customer_name:
                converter: 'anonymizeText'
            billing_name:
                converter: 'anonymizeText'
            shipping_name:
                converter: 'anonymizeText'
            billing_address:
                converter: 'anonymizeText'
            shipping_address:
                converter: 'anonymizeText'

    # Not anonymized: cc_exp_month, cc_exp_year, cc_ss_start_month, cc_ss_start_year
    sales_order_payment:
        converters:
            last_trans_id:
                converter: 'anonymizeNumber'
            cc_trans_id:
                converter: 'anonymizeNumber'
            cc_owner:
                converter: 'anonymizeText'
            cc_approval:
                converter: 'anonymizeText'
            cc_number_enc:
                converter: 'anonymizeText'
            cc_last_4:
                converter: 'anonymizeNumber'
            cc_debug_request_body:
                converter: 'anonymizeText'
            cc_debug_response_body:
                converter: 'anonymizeText'
            cc_debug_response_serialized:
                converter: 'anonymizeText'
            echeck_account_name:
                converter: 'anonymizeText'
            echeck_bank_name:
                converter: 'anonymizeText'
            additional_information:
                converter: 'jsonData'
                parameters:
                    converters: {CC_CN: 'anonymizeText', method_title: 'anonymizeText'}

    sales_shipment:
        converters:
            customer_note:
                converter: 'faker'
                parameters: {formatter: 'text'}

    sales_shipment_comment:
        converters:
            comment:
                converter: 'faker'
                parameters: {formatter: 'text'}

    sales_shipment_grid:
        converters:
            customer_email:
                converter: 'anonymizeText'
            customer_name:
                converter: 'anonymizeText'
            billing_name:
                converter: 'anonymizeText'
            shipping_name:
                converter: 'anonymizeText'
            billing_address:
                converter: 'anonymizeText'
            shipping_address:
                converter: 'anonymizeText'

    sales_shipment_track:
        converters:
            track_number:
                converter: 'anonymizeText'

if_version:
    '>=2.2':
        tables:
            # These tables did not exist before Magento 2.2
            email_abandoned_cart:
                converters:
                    email:
                        converter: 'randomizeEmail'

            email_automation:
                converters:
                    email:
                        converter: 'randomizeEmail'

            email_campaign:
                converters:
                    email:
                        converter: 'randomizeEmail'

            email_contact:
                converters:
                    email:
                        converter: 'randomizeEmail'

            email_order:
                converters:
                    email_imported:
                        converter: 'randomizeEmail'

    '<2.2':
        tables:
            # Before Magento 2.2, additional data was serialized instead of JSON-encoded
            quote_payment:
                converters:
                    additional_information:
                        converter: 'serializedData'

            sales_order_payment:
                converters:
                    additional_information:
                        converter: 'serializedData'
