---
extends: magento2

tables:
    magento_giftregistry_entity:
        converters:
            title:
                converter: 'anonymizeText'
            message:
                converter: 'anonymizeText'
            shipping_address:
                converter: 'jsonData'
                parameters:
                    converters:
                        firstname:
                            converter: 'anonymizeText'
                        middlename:
                            converter: 'anonymizeText'
                        lastname:
                            converter: 'anonymizeText'
                        company:
                            converter: 'anonymizeText'
                        street:
                            converter: 'anonymizeText'
                        postcode:
                            converter: 'randomizeNumber'
                        city:
                            converter: 'anonymizeText'
                        telephone:
                            converter: 'randomizeNumber'
                        fax:
                            converter: 'randomizeNumber'

    magento_giftregistry_person:
        converters:
            email:
                converter: 'randomizeEmail'
            firstname:
                converter: 'anonymizeText'
            lastname:
                converter: 'anonymizeText'

    magento_invitation:
        converters:
            email:
                converter: 'randomizeEmail'
            message:
                converter: 'anonymizeText'

    magento_rma:
        converters:
            customer_custom_email:
                converter: 'randomizeEmail'

    magento_rma_shipping_label:
        converters:
            track_number:
                converter: 'anonymizeText'

    magento_rma_status_history:
        converters:
            comment:
                converter: 'faker'
                parameters: {formatter: 'text'}

    magento_sales_creditmemo_grid_archive:
        converters:
            customer_email:
                converter: 'randomizeEmail'
            customer_name:
                converter: 'anonymizeText'
            billing_name:
                converter: 'anonymizeText'
            billing_address:
                converter: 'anonymizeText'
            shipping_address:
                converter: 'anonymizeText'
            shipping_information:
                converter: 'anonymizeText'

    magento_sales_invoice_grid_archive:
        converters:
            customer_email:
                converter: 'randomizeEmail'
            customer_name:
                converter: 'anonymizeText'
            billing_name:
                converter: 'anonymizeText'
            billing_address:
                converter: 'anonymizeText'
            shipping_address:
                converter: 'anonymizeText'
            shipping_information:
                converter: 'anonymizeText'

    magento_sales_order_grid_archive:
        converters:
            customer_email:
                converter: 'randomizeEmail'
            customer_name:
                converter: 'anonymizeText'
            billing_name:
                converter: 'anonymizeText'
            shipping_name:
                converter: 'anonymizeText'
            billing_address:
                converter: 'anonymizeText'
            shipping_address:
                converter: 'anonymizeText'
            shipping_information:
                converter: 'anonymizeText'

    magento_sales_shipment_grid_archive:
        converters:
            customer_email:
                converter: 'randomizeEmail'
            customer_name:
                converter: 'anonymizeText'
            billing_name:
                converter: 'anonymizeText'
            shipping_name:
                converter: 'anonymizeText'
            billing_address:
                converter: 'anonymizeText'
            shipping_address:
                converter: 'anonymizeText'
            shipping_information:
                converter: 'anonymizeText'
