---
extends: magento2

tables:
    magento_giftregistry_entity:
        converters:
            title: 'anonymizeText'
            message: 'anonymizeText'
            shipping_address: 'anonymizeText'

    magento_giftregistry_person:
        converters:
            email: 'randomizeEmail'
            firstname: 'anonymizeText'
            lastname: 'anonymizeText'

    magento_invitation:
        converters:
            email: 'randomizeEmail'
            message: 'anonymizeText'

    magento_rma:
        converters:
            customer_custom_email: 'randomizeEmail'

    magento_sales_creditmemo_grid_archive:
        converters:
            customer_email: 'randomizeEmail'
            customer_name: 'anonymizeText'
            billing_name: 'anonymizeText'
            billing_address: 'anonymizeText'
            shipping_address: 'anonymizeText'
            shipping_information: 'anonymizeText'

    magento_sales_invoice_grid_archive:
        converters:
            customer_email: 'randomizeEmail'
            customer_name: 'anonymizeText'
            billing_name: 'anonymizeText'
            billing_address: 'anonymizeText'
            shipping_address: 'anonymizeText'
            shipping_information: 'anonymizeText'

    magento_sales_order_grid_archive:
        converters:
            customer_email: 'randomizeEmail'
            customer_name: 'anonymizeText'
            billing_name: 'anonymizeText'
            shipping_name: 'anonymizeText'
            billing_address: 'anonymizeText'
            shipping_address: 'anonymizeText'
            shipping_information: 'anonymizeText'

    magento_sales_shipment_grid_archive:
        converters:
            customer_email: 'randomizeEmail'
            customer_name: 'anonymizeText'
            billing_name: 'anonymizeText'
            shipping_name: 'anonymizeText'
            billing_address: 'anonymizeText'
            shipping_address: 'anonymizeText'
            shipping_information: 'anonymizeText'
