---
requiresVersion: true

tables:
    # TODO index, tmp, replica

    cron_schedule:
        truncate: true

    customer_log:
        truncate: true

    customer_visitor:
        truncate: true

    cache:
        truncate: true

    cache_tag:
        truncate: true

    admin_user_session:
        truncate: true

    persistent_session:
        truncate: true

    #catalog_product_entity:
    #    limit: 2
    #    orderBy: 'sku asc, entity_id desc'
    #    filters:
    #        - ['entity_id', 'isNotNull']
    #        - ['sku', 'isNotNull']
    #        - ['type_id', 'in', ['simple', 'configurable']]

    #sales_order:
    #    truncate: true

    customer_entity:
        converters:
            email: { converter: 'anonymizeEmail', unique: true }
            firstname: 'anonymizeText'
            lastname: 'anonymizeText'
            password_hash: 'anonymizeText'
            failures_num: { converter: 'setValue', parameters: { value: 0 } }
            lock_expires: 'setNull'

# todo: serializedData instead of jsonData in some tables
#if_version:
#    '<2.2.0':
#        # Version-specific config here
