---
extends: magento1

tables:
    '*_cl':
        truncate: true

    enterprise_admin_passwords:
        truncate: true

    enterprise_logging_event:
        truncate: true

    enterprise_logging_event_changes:
        truncate: true

    enterprise_giftregistry_entity:
        converters:
            title: 'anonymizeText'
            message: 'anonymizeText'
            shipping_address:
                converter: 'serializedData'
                parameters:
                    converters:
                        firstname:
                            converter: 'anonymizeText'
                        middlename:
                            converter: 'anonymizeText'
                        lastname:
                            converter: 'anonymizeText'
                        company:
                            converter: 'anonymizeText'
                        street:
                            converter: 'anonymizeText'
                        postcode:
                            converter: 'randomizeNumber'
                        city:
                            converter: 'anonymizeText'
                        telephone:
                            converter: 'randomizeNumber'
                        fax:
                            converter: 'randomizeNumber'

    enterprise_giftregistry_person:
        converters:
            email:
                converter: 'randomizeEmail'
            firstname:
                converter: 'anonymizeText'
            middlename:
                converter: 'anonymizeText'
            lastname:
                converter: 'anonymizeText'

    enterprise_rma:
        converters:
            customer_custom_email:
                converter: 'randomizeEmail'

    enterprise_rma_grid:
        converters:
            customer_name:
                converter: 'anonymizeText'

    enterprise_rma_shipping_label:
        converters:
            track_number:
                converter: 'anonymizeText'

    enterprise_rma_status_history:
        converters:
            comment:
                converter: 'faker'
                parameters: {formatter: 'text'}

    enterprise_sales_creditmemo_grid_archive:
        converters:
            billing_name:
                converter: 'anonymizeText'

    enterprise_sales_invoice_grid_archive:
        converters:
            billing_name:
                converter: 'anonymizeText'

    enterprise_sales_order_grid_archive:
        converters:
            billing_name:
                converter: 'anonymizeText'
            shipping_name:
                converter: 'anonymizeText'

    enterprise_sales_shipment_grid_archive:
        converters:
            shipping_name:
                converter: 'anonymizeText'
